config/routes.rb
Rails.application.routes.draw do
  resources :records

  root :to => 'main#index'
  get 'main/index'

  get 'main/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @records.to_json }
    end
  end

  def new 
    @record = Record.new       
  end

  def create
    @record = Record.new(record_params)
    @record.save

    redirect_to :action => :index 
  end

  def show
    @record = Record.find(params[:id])
    respond_to do |format|
      format.html { @page_title = @record.id} # show.html.erb
      format.json { render :json => @record.to_json }
    end
  end


  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    redirect_to records_url
  end

  private

  def record_params
    params.require(:record).permit(:latitude, :longtitude, :device_id, :created_at) 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
          <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/index.html.erb
<style>
.article-h2{
  color: rgba(5, 5, 134, 0.34);
  margin-top:40px;
}

.article-block {
  margin-top: 31px;
  padding-left: 50px;
}
</style>


<div class="container" style="padding-top:20px; padding-left:5%; padding:right:5%;">
  <div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10" style="padding-bottom:100px;">
      <!-- tab nav -->
      <ul class="nav nav-tabs" style="padding-left:5%">
        <li class="active"><a data-toggle="tab" href="#about">關於我</a></li>
        <li><a data-toggle="tab" href="#program-note">程設雜筆</a></li>
        <li><a data-toggle="tab" href="#course-note">修課筆記</a></li>
        <li><a data-toggle="tab" href="#life-note">生活見聞</a></li>
      </ul>

      <!-- tab content - About Me -->
      <div class="tab-content" style="padding-top:5%; padding-left:5%; padding-right:5%;">
        <div id="about" class="tab-pane fade in active">
          <h1>Chiwei Hsiao</h1>
          <!--article block START-->
          <div class="article-block">
            <h2 class='article-h2'>Contact</h2>
            <ul>
              <li>kiwi010379@gmail.com</li>
              <li><a href="https://github.com/ChiWeiHsiao">GitHub</a></li>
              <li><a href="https://www.linkedin.com/in/chiwei-hsiao">Linkedin</a></li>
              <li><a href="https://www.facebook.com/profile.php?id=100001985286849">facebook</a></li>
            </ul>
            <h2 class='article-h2'>Education</h2>
            <ul>
              <li>B.S. Dept. of Computer Science, National Chiao Tung University, Hsinchu, Taiwan, 2014 - now.</li>
            </ul>
            <h2 class='article-h2'>Experiences</h2>
            <ul>
              <li><a href="https://plus.nctu.edu.tw/">NCTU+</a> Backend Engineer</li>
              <li>NCTU CS Tennis Team Leader</li>
            </ul>
            <h2 class='article-h2'>Awards</h2>
            <ul>
              <li>Academic Achievement Award - NCTU (February 2016)</li>
              <li>Academic Achievement Award - NCTU (September 2016)</li>
            </ul>
            <h2 class='article-h2'>Skills & Interest</h2>
            <ul>
              <li>Programming Language: C++, python, ruby</li>
              <li>Website Development: ROR back-end / Basic front-end</li>
              <li>Machine Learning ( still learning XD )</li>
            </ul>
          </div>
        </div>

        <!-- tab-程設雜筆 -->
        <div id="program-note" class="tab-pane fade">
          <p>假的 OwO</p>
        </div>
        <!-- tab-課程雜筆 -->
        <div id="course-note" class="tab-pane fade">
          <p>假的 OwO</p>
        </div>
        <!-- tab-生活見聞 -->
        <div id="life-note" class="tab-pane fade">
          <p>假的 OwO</p>
        </div>
      </div>
      <!--tab content - END -->
  </div>
</div>
</div>

app/views/records/index.html.erb
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>The HTML5 Herald</title>
    <meta name="description" content="The HTML5 Herald">
    <meta name="author" content="SitePoint">

    <link rel="stylesheet" href="css/styles.css?v=1.0">

    <link rel="stylesheet" href="css/styles.css">

    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ASUS GeoTag</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="./index.html">Dashboard</a></li>
            <li><a href="./storage.html">Storage</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sorting<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="./sort-by-date.html">Date</a></li>
                <li><a href="./sort-by-location.html">Location</a></li>
                <li><a href="./sort-by-device.html">Device ID</a></li>
              </ul>
            </li>
            <li><a href="#">Image Processing</a></li>
            <li><a href="#">Error Detection</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Language</a></li>
                <li><a href="#">Sign Out</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="js/scripts.js"></script>


    <h1>總表</h1>
    <%= link_to '新增', new_record_path, class:"btn btn-info", style:"font-size:20px; margin-top:10px; margin-bottom:10px;" %>
      <table class = "table table-striped"> 
        <tbody>
          <% @records.each do |r| %>
            <tr>
              <td> <%= r.longitude%> </td>
              <td > <%= r.latitude%> </td>
              <td > <%= r.device_id%> </td>
              <td align="right" width="50px" style="font-size:20px;"> <%= link_to '查看', record_path(r) %>  </td>
              <td align="right" width="50px" style="font-size:20px;"> <%= link_to '刪除', record_path(r), :method => :delete, :data => { :confirm => "Are you sure?" } %></td> 
            </tr>
          <%end%>
        </tbody>
      </table>


  </body>
</html>

app/views/records/new.html.erb
<div id="main-container" class="container bg-white" style="padding-left:100px; padding-right:150px; padding-bottom:100px;">
  <h1 style="margin-bottom:40px;"> 更新成員資料 </h1>
  <%= form_for @record ,:html=>{class: "form-horizontal", role:"form", id:"member-form"} do |f| %>


    <div class="form-group">
      <label class="col-sm-2 control-label">longtitude:</label>
      <div class="col-sm-10">
        <%= f.number_field :latitude, :step => "0.01", class:"form-control",  placeholder:"ex.94.87" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">longtitude:</label>
      <div class="col-sm-10">
        <%= f.number_field :longitude, :step => "0.01", class:"form-control",  placeholder:"ex.94.87" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">device_id:</label>
      <div class="col-sm-10">
        <%= f.number_field :device_id, class:"form-control",  placeholder:"the id of the camera" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">上傳圖片</label>
      <div class="col-sm-10">
        <%#= f.file_field :member_image %>
      </div> 
    </div>

    <div align="right"  style="margin-top:15px; margin-bottom:15px"> 
      <%=f.submit "送出",class:"btn btn-lg btn-info"%>
    </div>

  <% end %>
</div>